### ISSUE TITLE
FPGA core ? MIST / MISTer

### ISSUE THREAD

**Issue by juanpc2018** [dsp56300/gearmulator#169]
MIST has a Cyclone 3 "as cheap as possible", but much faster than Motorola 68060 100MHz
https://lotharek.pl/productdetail.php?id=45
see Amiga Drystone tests.
MIST >v1.4 has MIDI.

MISTer "a fork" does Not have MIDI, uses a Dev.Board called DE10 nano.
Cyclone5, twice more $$.

New Intel / Altera Cyclone10 are super fast, 3x Cyclone5.
 
The problem with CPU emulation, is 2:
A) CPU have interrupts, 10Mhz, audio algorithms do Not like to be interrupted,
B) Branch prediction algorithms, 
CPU cheat, and fake being faster, by interrupting & predicting the result before CPU can complete the result,
No prediction algorithm is 100% accurate,
if you interrupt for too long "more than 32 Buffer size" CPU needs giant L1/L2/L3 cache "Not available in most CPUs".

thats why Protools HDX still king, and CPU is Hobby.
No Matter how good the code is, CPU will never sound the same, or have the same latency,
Close but Not the same.

questions:
¿can DSP56300 core work in Cyclone3 "MIST"  ? 
¿can DSP56300 core work in Cyclone5 "MISTer" ? 
im sure it can in Cyclone10, there is No doubt.
but there is No cores nor boards for C10.

**Comment by mkruselj** [comment]
I think the answer is "no" here.

**Comment by dsp56300** [comment]
Even though there might be a lot of FPGAs/ASICs/etc that can emulate the DSP theoretically, the goal for us is to make it work on consumer grade hardware such as x86 and aarch64 CPUs so that the synths are preserved and easily accessible for everyone.

If other architectures shall be targeted it is best to fork this project (or the DSP project) but its not something that we have on our roadmap
