### ISSUE TITLE
Unusual install location for vst2 and vst3 on Linux

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#87]
<@770574624953073665>,<#841809045505703956>,Re the .deb files for Linux. The install locations are not typically used (it’s dropping to /usr/local/lib/ which means users having to add additional DAW paths to plugins. Typically you want VSTs in either /home/username/vst  or /home/.username/vst3 (which are the most convenient ones, doubly so because the Rom can then be put in the plug-in folder alongside without using sudo) or /usr/lib/vst /usr/lib/vst3 -less convenient because you then have to use sudo, plus a lot of users will copy the folders to home anyway to keep plugins out of root. Also I e noticed the file structure for the VST3 isn’t right. It only drops a .so file (as per vst2), vst3 files go in a /plug-in name.vst3/Contents/x86_64-linux/pluginname.so,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/963032063659884625)

**Comment by dromer** [comment]
Er, `/usr/local/lib/` is the correct place to put these files. A .deb package is installed globally, not to the home-folder of the user that runs the installer.

Because the .deb is a third party installer `/usr/local/lib` is the appropriate location. If the installation was done through a repository it should go to `/usr/lib` locations.

If you really only want to install to the home-dir you should write an installation-script to take individual files and place them there.

Now, because dsp56300 requires a rom file to be manually placed located next to the plugin (that is still a requirement, correct?) the install-script maybe makes most sense. But installing a .deb in to the home-dir is really bad practice!

**Comment by dsp56300** [comment]
Thanks for clarifying this, other people reported that it should be the users home directory but your explanation makes sense.
Should the plugins go into a subfolder such as ``/usr/lib/vst`` and ``/usr/lib/vst3`` @dromer?

**Comment by dsp56300** [comment]
Sorry, saw it in the other ticket. So, the final installation targets should be:
``/usr/local/lib/vst``
``/usr/local/lib/vst`3``
Can you confirm @dromer ?

**Comment by dromer** [comment]
Yes, those should be the correct paths for a 3rd party .deb installation.

Is the requirement to have the ROM file next to the plugin installation still present? Because this complicates installation for users of course.
Otherwise it's likely better to have a tarball with install-script for the HOME folder, because then users will have to figure out the ROM installation on their own.

A package manager install should really not touch things in the HOME dir, that's for certain at least :)
